# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c415bbabc80122b54df2b360156a5815bfc3bb65c202e65d2f3dadf311fa8f3defc1447648ea060893e696835ae1b1b06aba4e25ac58f509301f87d34215fa8

test:
  secret_key_base: 73daadf14a7a3d3f78b851b285dc539d3ae702f25370a4c8db728c9ee260860fe6d5dea89dbad6b3cd60fed8b27d270f31077b2a7d357e63f04554556c883d1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
